"""Code Agent - generates code changes based on GitHub Issues."""

from agno.agent import Agent
from agno.models.openrouter import OpenRouter

from src.core.config import get_settings
from src.github.client import GitHubClient, IssueData
from src.tools.code_tools import create_code_tools


CODE_AGENT_PROMPT = """You are a skilled software developer. Your task is to implement changes in a codebase based on GitHub Issue requirements.

RULES:
1. First, explore the codebase structure using list_files
2. Read relevant files before making changes
3. Make minimal, focused changes that address the issue
4. Write clean, well-documented code
5. Follow existing code style and patterns
6. Create or update tests if needed
7. Use descriptive commit messages

WORKFLOW:
1. Understand the issue requirements
2. Explore the codebase to find relevant files
3. Plan your changes
4. Implement changes using write_file
5. Verify your changes make sense

Always explain your reasoning before making changes.
Respond in English.
"""


class CodeAgent:
    """Agent that generates code changes based on Issues."""

    def __init__(
        self,
        github_client: GitHubClient | None = None,
        model: str | None = None,
    ):
        settings = get_settings()
        self.github = github_client or GitHubClient()
        self.model = model or settings.default_model
        self.api_key = settings.llm_api_key
        self.max_iterations = settings.max_iterations

    def process_issue(self, issue_number: int) -> dict:
        """Process an issue and create a PR with changes.

        Returns:
            dict with keys: success, pr_number, branch, message
        """
        # Get issue data
        issue = self.github.get_issue(issue_number)

        # Create branch for changes
        branch_name = f"issue-{issue_number}-auto"
        self.github.create_branch(branch_name)

        # Create tools with branch context
        tools = create_code_tools(self.github, branch_name)

        # Create agent
        agent = Agent(
            model=OpenRouter(id=self.model, api_key=self.api_key),
            tools=tools,
            instructions=CODE_AGENT_PROMPT,
            markdown=True,
        )

        # Build prompt with issue context
        prompt = self._build_prompt(issue)

        # Run agent
        try:
            response = agent.run(prompt)

            # Create PR
            pr_number = self.github.create_pull_request(
                title=f"Fix #{issue_number}: {issue.title}",
                body=self._create_pr_body(issue, response.content),
                head=branch_name,
            )

            return {
                "success": True,
                "pr_number": pr_number,
                "branch": branch_name,
                "message": "PR created successfully",
            }
        except Exception as e:
            return {
                "success": False,
                "pr_number": None,
                "branch": branch_name,
                "message": f"Error: {str(e)}",
            }

    def _build_prompt(self, issue: IssueData) -> str:
        """Build prompt for the agent."""
        return f"""Please implement the following GitHub Issue:

## Issue #{issue.number}: {issue.title}

{issue.body}

---

Start by exploring the codebase, then implement the required changes.
"""

    def _create_pr_body(self, issue: IssueData, agent_response: str) -> str:
        """Create PR description."""
        return f"""## Summary
Automated fix for #{issue.number}

## Related Issue
Closes #{issue.number}

## Changes Made
{agent_response[:1000]}...

---
*Generated by SDLC Code Agent*
"""

    def apply_review_feedback(
        self,
        pr_number: int,
        feedback: str,
        branch: str,
    ) -> dict:
        """Apply changes based on reviewer feedback.

        Returns:
            dict with keys: success, message
        """
        # Create tools with branch context
        tools = create_code_tools(self.github, branch)

        # Create agent
        agent = Agent(
            model=OpenRouter(id=self.model, api_key=self.api_key),
            tools=tools,
            instructions=CODE_AGENT_PROMPT,
            markdown=True,
        )

        prompt = f"""The reviewer has requested changes to PR #{pr_number}.

## Reviewer Feedback:
{feedback}

Please address these concerns by making the necessary code changes.
Start by reading the relevant files, then make targeted fixes.
"""

        try:
            response = agent.run(prompt)

            # Add comment to PR
            self.github.add_pr_comment(
                pr_number,
                f"Applied fixes based on review feedback:\n\n{response.content[:500]}...",
            )

            return {
                "success": True,
                "message": "Feedback addressed",
            }
        except Exception as e:
            return {
                "success": False,
                "message": f"Error: {str(e)}",
            }
